#!/bin/sh

bspc config border_width        0
bspc config window_gap          24

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5 6 7 8 9 m c

$DOTFILES/bspwm./panel &
dunst &
