#!/bin/sh

COLOR_ACTIVE='#FFFFFADF'
COLOR_INACTIVE='#55FFFADF'
COLOR_IMPORTANT='#55FFFADF'

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
    case $line in
        S*)
            # clock output
            sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
            ;;
        T*)
            # xtitle output
            title="%{F$COLOR_TITLE_FG} ${line#?} %{B-}%{F-}"
            ;;
        X*)
            # arbitrary output
            title="${line#?}"
            ;;
        W*)
            # bspwm internal state
            IFS=':' && declare -a items=("${line#?}")
            echo "$items" 1>&2

            wm_infos=""
            for item in $items; do
                name=${item#?}
                case $item in
                    M*)
                        # active monitor
                        if [ $num_mon -gt 1 ] ; then
                            wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG} ${name} %{B-}%{F-}  "
                        fi
                        ;;
                    m*)
                        # inactive monitor
                        if [ $num_mon -gt 1 ] ; then
                            wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG} ${name} %{B-}%{F-}  "
                        fi
                        ;;
                    O*|F*|U*)
                        # focused desktop
                        wm_infos="${wm_infos}%{F$COLOR_ACTIVE} ${name} %{F-}"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="${wm_infos}%{F$COLOR_INACTIVE} ${name} %{F-}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="${wm_infos}%{F$COLOR_IMPORTANT} ${name} %{F-}"
                        ;;
                    f*)
                        # free desktops aren't drawn
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "%{l}${wm_infos}%{r}${title}"
done
